module.exports = {
    normal : ':fish_cake:' ,
    fighting : ':boxing_glove:',
    flying: ':eagle:',
    poison: ':mushroom:',
    ground: ':desert:',
    rock: ':mountain:',
    bug: ':lady_beetle: ',
    ghost: ':ghost:',
    steel: ':mechanical_arm:',
    fire: ':fire:',
    water: ':droplet:',
    grass: ':four_leaf_clover:',
    electric: ':zap:',
    psychic: ':candy:',
    ice: ':snowflake:',
    dragon: ':dragon:',
    dark: ':dark_sunglasses:',
    fairy: ':woman_fairy:'
};